experiment_name: "DPM solver"
experiment:
  method: "dpm_sovler"
  seed: 29
model:
  model_name: "stable_diffusion_model"
  pretrained_model: "runwayml/stable-diffusion-v1-5"
dataset:
  img_dataset: "./data/dataset/test/"
  prompts: "./data/dataset/img2annotations_test.json"
  image_size: 512
quality_metrics:
  clip_score:
    model_name_or_path: "openai/clip-vit-base-patch16"
  image_reward:
    model_name: "ImageReward-v1.0"
  fid:
    feature: 64
    input_img_size: 512
    normalize: False
logger:
  wandb_enable: True
  project_name: "Sonic diffusion"
  log_images_step: 2
inference:
  batch_size: 32
experiment_params:
  algorithm_type: 'dpmsolver'
  final_sigmas_type: "sigma_min"
  solver_order: 2
  num_train_timesteps: 1000
  num_inference_steps: [5, 10, 20]