experiment_name: "Deep cache"
experiment:
  method: deep_cache
  seed: 29
model:
  model_name: stable_diffusion_model
  pretrained_model: runwayml/stable-diffusion-v1-5
dataset:
  img_dataset: "./data/dataset/test/"
  prompts: "./data/dataset/img2annotations_test.json"
  image_size: 512
quality_metrics:
  clip_score:
    model_name_or_path: "openai/clip-vit-base-patch16"
  image_reward:
    model_name: "ImageReward-v1.0"
  fid:
    feature: 64
    input_img_size: 512
    normalize: False
speed_metrics: ['time_metric']
logger:
  wandb_enable: True
  project_name: "Sonic diffusion"
inference:
  batch_size: 4
experiment_params:
  algorithm_type: 'dpmsolver'
  solver_order: 2
  num_train_timesteps: 1000
  num_inference_steps: [5, 10 , 20]