experiment_name: "DPM solver"
experiment:
  method: "DPM and DDIM"
  seed: 29
model:
  model_name: "stable_diffusion_model_two_schedulers"
  pretrained_model: "runwayml/stable-diffusion-v1-5"
scheduler:
  scheduler_first: "dpm_solver_scheduler"
  scheduler_second: "ddim_scheduler"
dataset:
  img_dataset: "./data/dataset/test/"
  prompts: "./data/dataset/img2annotations_test.json"
  image_size: 512
quality_metrics:
  clip_score:
    model_name_or_path: "openai/clip-vit-base-patch16"
  image_reward:
    model_name: "ImageReward-v1.0"
  fid:
    feature: 64
    input_img_size: 512
    normalize: False
logger:
  wandb_enable: True
  project_name: "Sonic diffusion"
  log_images_step: 1
  save: True
  save_dir: "./data/generate_images/{experiment}/{args}/"
inference:
  batch_size: 32
experiment_params:
  solver_order: 2
  num_inference_steps_first: [10, 20, 30]
  num_inference_steps_second: [10, 20, 30]
  num_step_switch: [5, 5, 5]